import { GetServerSideProps } from "next";
import {
  getSession,
  RedirectableProvider,
  signIn,
  useSession,
} from "next-auth/react";
import Head from "next/head";
import styles from "../styles/Home.module.css";

type T = RedirectableProvider | "github";

export default function Home() {
  const { data } = useSession();
  const _typesafe = useSession({ required: false });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App with Prisma and Next-Auth V4</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Aaaaaa</div>
      {data && <div>User: {data.user?.name}</div>}
      {!data && (
        <>
          <button onClick={() => signIn("github")}>Sign In with Github</button>
          <button onClick={() => signIn<"github">("github")}>
            Sign In with Github
          </button>
          <button
            onClick={() => signIn<RedirectableProvider | "github">("github")}
          >
            Sign In with Github
          </button>
        </>
      )}
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getSession({ req: context.req });

  return { props: { session, hideTopNav: !session } };
};
